name: Locust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stress-test:
    name: Locust stress test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install locust
        run: python -m pip install locust

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: minicap:latest

      - name: Run Docker image
        run: docker run -d -p 8000:8000 minicap

      - name: Wait for Docker image to start
        run: sleep 5

      - name: Run locust
        run: |
          locust -f ./test/locust/locustfile.py --headless \
            --users 30 --spawn-rate 5 --run-time 1m --only-summary\
            --host http://localhost:8000
