name: Style

on:
  push:
    branches:
      - master

jobs:
  auto-format:
    name: Lint & format code with ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install project dev dependencies
        run: uv sync --frozen --only-dev

      - name: Lint & format code with ruff and commit any changes
        run: |
          uv run --frozen ruff check --output-format=github --fix .
          uv run --frozen ruff format .
          git config --global user.name 'Auto ruff formatter'
          git config --global user.email 'claudiugeorgiu@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout ${GITHUB_REF#refs/heads/}
          git diff --quiet || git commit -am "Format code with ruff [auto]" && git push
